<a href="https://colab.research.google.com/github/neharaju27/neha/blob/main/python_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target
print("First 10 rows of the dataset:")
print(df.head(10))
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nData types of each column:")
print(df.dtypes)
print("\nNumber of unique values in each column:")
print(df.nunique())

First 10 rows of the dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7   

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("/content/housing.csv")
column='unique values'
Q1=df[column].quantile(0.25)
Q3=df[column].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
outliers=df[(df[column]<lower_bound) | (df[column]>upper_bound)]
print(f"Outliers in '{column}' column:")
print(outliers)
plt.figure(figsize=(10,6))
sns.boxplot(x=df[column])
plt.title(f'Box Plot of {column}')
plt.show()
df_no__outliers=df[(df[column]>=lower_bound) & (df[column]<=upper_bound)]
df[column]=np.where((df[column]<lower_bound) | (df[column]> upper_bound),df[column].median(),df[column])
print("\nOutliers handled using two method: 1) Removal 2) Replacement with median")

KeyError: 'unique values'

In [3]:
import numpy as np
np.random.seed(42)
matrix=np.random.randint(1,101,size=(10,10))
print("10*10 Matrix:\n",matrix)
row_sum=matrix.sum(axis=1)
print("\nRow-wise Sum:\n",row_sum)
column_sum=matrix.sum(axis=0)
print("\nColumn-wise sum:\n",column_sum)
transpose_matrix=matrix.T
print("\nTranspose of the matrix:\n",transpose_matrix)
trace_value=np.trace(transpose_matrix)
print("\nTrace of the transpose:\n",trace_value)

10*10 Matrix:
 [[ 52  93  15  72  61  21  83  87  75  75]
 [ 88 100  24   3  22  53   2  88  30  38]
 [  2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47]
 [ 62  51  55  64   3  51   7  21  73  39]
 [ 18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36]
 [ 50   4   2   6  54   4  54  93  63  18]
 [ 90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24]]

Row-wise Sum:
 [634 448 474 610 426 423 552 348 576 663]

Column-wise sum:
 [617 557 479 498 357 526 438 681 576 425]

Transpose of the matrix:
 [[ 52  88   2  91  62  18  92  50  90  72]
 [ 93 100  64  59  51   4  60   4  44  78]
 [ 15  24  60  42  55  89  71   2  34  87]
 [ 72   3  21  92  64  60  44   6  74  62]
 [ 61  22  33  60   3  14   8  54  62  40]
 [ 21  53  76  80  51   9  47   4 100  85]
 [ 83   2  58  15   7  90  35  54  14  80]
 [ 87  88  22  62  21  53  78  93  95  82]
 [ 75  30  89  62  73   2  81  63  48  53]
 [ 75  38  49  47  39

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("/content/winequality-red.csv")
df=df.dropna(how="all")
df=df.fillna(0)
numerical_data=df.select_dtypes(include=[float,int])
if numerical_data.empty:
  print("No numerical columns found in the dataset")
else:
 corr_matrix=numerical_data.corr()
 plt.figure(figsize=(8,6))
 sns.heatmap(corr_matrix,annot=True,cmap='coolwarm',square=True,linewidths=0.5)
 plt.title("Correlation Heatmap of Numerical Variables")
 plt.show()

No numerical columns found in the dataset


In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("/content/winequality-white.csv")
df=df.dropna(how="all")
df=df.fillna(0)
numerical_data=df.select_dtypes(include=[float,int])
if numerical_data.empty:
  print("No numerical columns found in the dataset")
else:
 corr_matrix=numerical_data.corr()
 plt.figure(figsize=(8,6))
 sns.heatmap(corr_matrix,annot=True,cmap='coolwarm',square=True,linewidths=0.5)
 plt.title("Correlation Heatmap of Numerical Variables")
 plt.show()

No numerical columns found in the dataset


In [ ]:
import pandas as pd
df=pd.read_csv("/content/adult.csv.zip")
def categorize_age(age):
  if age<=25:
    return 'Youth'
  elif age<=60:
    return 'Adult'
  else:
    return 'Senior'
df['Age_Category']=df['age'].apply(categorize_age)
print(df.head())
pivot_table=pd.pivot_table(df,values='fnlwgt',index='Age_Category',columns='gender',aggfunc='mean')
print(pivot_table)

   age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country incom